<%@ page import="java.util.*,immutable.occamsjsonds.*" %><%!
	static String wholeState = "{\"QuadCraft\":{\"p\":0, \"v\":0}}";
	
	//one copy of parts of the V/Var tree.
	//keys that start with lowercase are built in such as p v t.
	//Keys that start with Capital are childs like in V.Hello.World .
	//TODO maybe this should be made mutable so its faster,
	//but probably the network will be the bottleneck
	//if theres just a few players so dont worry about it for now.
	//Also, immutable may make threading easier
	//since you can many-read but one-write.
	static NavigableMap V = JsonDS.emptyMap;
	
	static boolean testedOccamsJsonDS = false;
	
	//object such as NavigableMap, List, Double.
	//May not have well tested true, false, and null,
	//as those were added to JsonDS later.
	static Object jsonToOb(String json){
		return JsonDS.jsonParse(json);
	}
	
	static String obToJson(Object ob){
		return JsonDS.jsonString(ob);
	}
	
	static String stringInStringOut(String i){
		System.out.println("\n\n\n\n\n\n\n\n");
		if(!testedOccamsJsonDS){
			System.out.println("START: test json");
			TestJsonDS.main(new String[0]);
			System.out.println("END: test json. Look at output, it doesnt throw if its broken, but its been working.");
			testedOccamsJsonDS = true;
		}
		System.out.println("in length = "+i);
		Object ob = jsonToOb(i); //probably a NavigableMap as json {}
		String action = (String)((NavigableMap)ob).get("action");
		if(action == null){
			action = "help";
		}
		System.out.println("action="+action);
		String o;
		switch(action){
			case "ok": //ignore this, just a message something succeeded, normally received from browser
				o = "{\"action\":\"ok\"}";
			break;case "help":
				o = "{\"action\":\"help\", \"comment\":\"Send json with a key of sparseVSync, readAll, writeAll, help, or ok. In sparseVSync, which is the only one you really need (others are early experiments or messages about the system), you also use a V key generated by V/Var in javascript such as V.QuadCraft.Room5.Hello.World or V.Bellsack.Room9 or V.Testnet . ns refers to the room as a shortcut such as ns.Hello.World . These all have .p (position) and .v (velocity) and sometimes other fields in them. Its for low lag sync of many-dimesional vectors of string named tree branches that all start with a capital letter.\"}";
			break; case "readAll":
				//FIXME merge wholeState (the early test) with "static NavigableMap V" (the main data)?
				o = wholeState;
			break; case "writeAll":
				//FIXME merge wholeState (the early test) with "static NavigableMap V" (the main data)?
				o = wholeState = i;
			break; case "sparseVSync":
				//the new code
				o = "{\"action\":\"sparseVSync\", \"comment\":\"TODO sparseVSync...\"}"; //FIXME
			break;default:
				throw new Error("Unknown action="+action);
		}
		System.out.println("stringInStringOut\nIN: "+i+"\nOUT: "+o);
		return o;
	}
%><%
	String body = request.getReader().lines().reduce("", (a,b)->(a+b));
	if(body == null || body.trim().equals("")){
		body = "{}";
	}
	String i = body; //in
	String o = stringInStringOut(i); //out
	response.setContentType("application/json");
	out.print(o);
%>