<%@ page import="java.util.*,java.util.function.Predicate,java.util.concurrent.*,immutable.occamsjsonds.*" %><%!
	/*
	NETWORK SYNC DESIGN
	- Var.js data still merges only by each Var's .t. Equal .t keeps the existing server value.
	- Tomcat stores one newest Var value per path in V.
	- Tomcat also stores server-only tNet beside each Var in that same server V tree.
	- Browser V data must not upload per-Var tNet, and Tomcat must not download per-Var tNet to browsers by default.
	- Sparse request selection is based on server-side per-Var tNet, not Var .t.
	- readSparse and readWriteSparse require peer.main.tNetFrom. That value is inclusive.
	- Tomcat returns peer.main.tNetFrom unchanged and peer.main.tNetTo from near the end of stringInStringOut.
	- Browser should use nextUp(previous peer.main.tNetTo) as the next peer.main.tNetFrom.
	- Tomcat stores no per-browser cursor or identity.
	- tNet is updated only when the server's stored .t for that Var changes.
	- If incoming .t is older or equal and does not replace server .t, do not refresh tNet.
	*/
	static String wholeState = "{\"QuadCraft\":{\"p\":0, \"v\":0}}";
	
	//one copy of parts of the V/Var tree.
	//keys that start with lowercase are built in such as p v t.
	//Keys that start with Capital are childs like in V.Hello.World .
	//TODO maybe this should be made mutable so its faster,
	//but probably the network will be the bottleneck
	//if theres just a few players so dont worry about it for now.
	//Also, immutable may make threading easier
	//since you can many-read but one-write.
	static volatile NavigableMap V = JsonDS.map("p",0., "v",0., "t",10000.); //root of V tree
	static final Object VLock = new Object();
	static boolean sendTNetPerVarToBrowser = false;
	static boolean includeTNetInShouldSendVar = true;
	static double allowTimeTravellersOnlyThisManySecondsAhead = 0.1;
	static boolean logRequestStartEnd = false;
	static boolean logInputJson = false;
	static boolean logOutputJson = false;
	static boolean logUrl = false;
	static boolean logAction = false;
	static boolean logLengths = true;
	static boolean logFutureRejects = true;
	static boolean logMissingTimeErrors = true;
	static boolean logJsonDsSelfTest = false;
	static boolean echoInputWithoutParsing = false;
	static final double timeAtStart = System.currentTimeMillis()*.001;
	static final long nanoAtStart = System.nanoTime();
	static double timeIdPrev = 0;
	static boolean doSystemGcEveryNSeconds = true;
	static double systemGcEveryNSeconds = 0.5;
	static double lastSystemGcTime = 0;
	
	static boolean testedOccamsJsonDS = false;
	
	static void logIf(boolean shouldLog, String s){
		if(shouldLog) System.out.println(s);
	}
	
	//object such as NavigableMap, List, Double.
	//May not have well tested true, false, and null,
	//as those were added to JsonDS later.
	static Object jsonToOb(String json){
		return JsonDS.jsonParse(json);
	}
	
	static String obToJson(Object ob){
		return JsonDS.jsonString(ob);
	}
	
	static String stringInStringOut(String i){
		double serverReceiveTime = TimeId();
		maybeSystemGc();
		if(echoInputWithoutParsing){
			TimeId();
			return i;
		}
		logIf(logRequestStartEnd, "START QuadCraftAjax request");
		if(!testedOccamsJsonDS){
			if(logJsonDsSelfTest){
				logIf(logJsonDsSelfTest, "START: test json");
				TestJsonDS.main(new String[0]);
				logIf(logJsonDsSelfTest, "END: test json. Look at output, it doesnt throw if its broken, but its been working.");
			}
			testedOccamsJsonDS = true;
		}
		Object ob = jsonToOb(i); //probably a NavigableMap as json {}
		String action = (String)((NavigableMap)ob).get("action");
		if(action == null){
			action = "help";
		}
		logIf(logAction, "action="+action);
		String o;
		boolean isReadWriteSparse = false;
		switch(action){
			case "ok": //ignore this, just a message something succeeded, normally received from browser
				o = "{\"action\":\"ok\"}";
			break;case "help":
				o = "{\"action\":\"help\", \"comment\":\"Send json with a key of sparseVSync, readAll, writeAll, help, or ok. In sparseVSync, which is the only one you really need (others are early experiments or messages about the system), you also use a V key generated by V/Var in javascript such as V.QuadCraft.Room5.Hello.World or V.Bellsack.Room9 or V.Testnet . ns refers to the room as a shortcut such as ns.Hello.World . These all have .p (position) and .v (velocity) and sometimes other fields in them. Its for low lag sync of many-dimesional vectors of string named tree branches that all start with a capital letter.\"}";
			break; case "readAll":
				//FIXME merge wholeState (the early test) with "static NavigableMap V" (the main data)?
				o = wholeState;
			break; case "writeAll":
				//FIXME merge wholeState (the early test) with "static NavigableMap V" (the main data)?
				o = wholeState = i;
			break; case "sparseVSync":
				//the new code
				o = "{\"action\":\"sparseVSync\", \"comment\":\"TODO sparseVSync...\"}"; //FIXME
			break; case "readWriteSparse":
				isReadWriteSparse = true;
				jsonGetDoubleElseThrow(ob,"peer","main","tNetFrom");
				//continue to writeSparse and then readSparse
			case "writeSparse":
				//o = "{\"action\":\"writeSparse\", \"comment\":\"TODO writeSparse...\"}"; //FIXME
				NavigableMap incoming = (NavigableMap)jsonGetElseThrow(ob,"V");
				synchronized(VLock){
					//in case 2 threads try to mod the tree at once. The tree is immutable (or at least used that way) but
					//we dont want other threads changes to get ignored. Keep the newest of each Var by Var.t.
					V = mergeMaps(V,incoming,serverReceiveTime); //update shared state on sever that multiple remote browsers sync with or parts of
				}
				if(!isReadWriteSparse){
					o = "{\"action\":\"ok\"}";
					break;
				}//else continue to readSparse
			case "readSparse": //maybe should be called readNewerThan (or readEqualTimeOrNewerThan).
				double tNetFrom = jsonGetDoubleElseThrow(ob,"peer","main","tNetFrom");
				NavigableMap mapOut = partsOfVTreeByMinTNet(V,tNetFrom);
				double tNetTo = TimeId();
				mapOut = JsonDS.map("action", "writeSparse", "V", mapOut, "comment", "This is the answer to a readSparse (action="+action+"), that should write into browser's V/Var tree.");
				mapOut = (NavigableMap)JsonDS.jsonSet(mapOut,"peer","main","tNetFrom",tNetFrom);
				mapOut = (NavigableMap)JsonDS.jsonSet(mapOut,"peer","main","tNetTo",tNetTo);
				o = obToJson(mapOut);
			break;default:
				throw new Error("Unknown action="+action);
		}
		logIf(logLengths, "action="+action+" inLen="+i.length()+" outLen="+o.length());
		logIf(logInputJson, "IN: "+i);
		logIf(logOutputJson, "OUT: "+o);
		logIf(logRequestStartEnd, "END QuadCraftAjax request");
		return o;
	}

	static Object jsonGetElseThrow(Object in,Object... path){
		Object ret = JsonDS.jsonGet(in,path);
		if(ret == null){
			throw new Error("Missing required json path: "+Arrays.asList(path));
		}
		return ret;
	}

	static double jsonGetDoubleElseThrow(Object in,Object... path){
		return (double)(Double)jsonGetElseThrow(in,path);
	}
	
	static NavigableMap partsOfVTreeByMinTime(NavigableMap fromNode, double minTime){
		Predicate<NavigableMap> keep = (NavigableMap node)->(minTime<=sparseReadTime(node));
		return partsOfVTree(fromNode, keep);
	}

	static NavigableMap partsOfVTreeByMinTNet(NavigableMap fromNode, double tNetFrom){
		Predicate<NavigableMap> keep = (NavigableMap node)->{
			double tNet = num(node,"tNet");
			return 0<tNet && tNetFrom<=tNet;
		};
		return partsOfVTree(fromNode, keep);
	}

	static double num(NavigableMap m, String key){
		Object x = m.get(key);
		return x instanceof Number ? ((Number)x).doubleValue() : 0.0;
	}

	static double sparseReadTime(NavigableMap m){
		double t = num(m,"t");
		return includeTNetInShouldSendVar ? Math.max(t,num(m,"tNet")) : t;
	}

	static double time(){
		return timeAtStart + (System.nanoTime()-nanoAtStart)*1e-9;
	}

	static synchronized double TimeId(){
		return timeIdPrev = Math.max(time(),Math.nextUp(timeIdPrev));
	}

	static synchronized double TimeIdNext(){
		return timeIdPrev = Math.nextUp(timeIdPrev);
	}

	static void maybeSystemGc(){
		if(!doSystemGcEveryNSeconds) return;
		double now = time();
		if(lastSystemGcTime+systemGcEveryNSeconds <= now){
			lastSystemGcTime = now;
			System.gc();
			logIf(true, "System.gc();");
		}
	}

	static boolean isIncomingTimeAllowed(NavigableMap node, double serverReceiveTime){
		return num(node,"t") <= serverReceiveTime + allowTimeTravellersOnlyThisManySecondsAhead;
	}

	static NavigableMap stampAcceptedIncoming(NavigableMap node, double serverReceiveTime){
		if(node==null)return null;
		boolean localAccepted = isIncomingTimeAllowed(node,serverReceiveTime);
		TreeMap out=new TreeMap(JsonDS.mapKeyComparator);
		if(localAccepted){
			for(Object k:node.keySet()){
				if(k.equals("pu")||k.equals("tNet")) continue;
				out.put(k,node.get(k));
			}
			double t=num(node,"t");
			if(t>0) out.put("tNet",TimeIdNext());
		}else{
			logIf(logFutureRejects, "Rejecting future incoming node t="+num(node,"t")+" serverReceiveTime="+serverReceiveTime+" node="+obToJson(node));
			out.put("p",0.);
			out.put("v",0.);
			out.put("t",0.);
		}
		NavigableMap pu=(NavigableMap)node.get("pu");
		TreeMap newPu=null;
		if(pu!=null){
			for(Object k:pu.keySet()){
				NavigableMap kept=stampAcceptedIncoming((NavigableMap)pu.get(k),serverReceiveTime);
				if(kept!=null){
					if(newPu==null)newPu=new TreeMap(JsonDS.mapKeyComparator);
					newPu.put(k,kept);
				}
			}
		}
		if(!localAccepted && newPu==null)return null;
		if(newPu!=null)out.put("pu",Collections.unmodifiableNavigableMap(newPu));
		return Collections.unmodifiableNavigableMap(out);
	}

	/** Copies every node that satisfies keep.test(node) or
	that has at least one descendant that does. minT <= node.t. minTime [replaced by tNet vars]
	*/
	static NavigableMap partsOfVTree(NavigableMap node, Predicate<NavigableMap> keep){
		return filterBranch(node,keep);
	}

	static NavigableMap filterBranch(NavigableMap node,Predicate<NavigableMap> keep){
		if(node==null)return null;
		boolean include=keep.test(node);
		NavigableMap pu=(NavigableMap)node.get("pu");
		NavigableMap newPu=null;
		if(pu!=null){
			for(Object k:pu.keySet()){
				NavigableMap kept=filterBranch((NavigableMap)pu.get(k),keep);
				if(kept!=null){
					if(newPu==null)newPu=new TreeMap(JsonDS.mapKeyComparator);
					newPu.put(k,kept);
				}
			}
			if(newPu!=null)include=true;
		}
		if(!include)return null;
		NavigableMap out=new TreeMap(JsonDS.mapKeyComparator);
		for(Object k:node.keySet()){
			if(k.equals("pu"))continue;
			if(k.equals("tNet") && !sendTNetPerVarToBrowser)continue;
			out.put(k,node.get(k));
		}
		if(newPu!=null)out.put("pu",Collections.unmodifiableNavigableMap(newPu));
		return Collections.unmodifiableNavigableMap(out);
	}
	
	static NavigableMap mergeMaps(NavigableMap a,NavigableMap b,double serverReceiveTime){
		Double ta=(Double)a.get("t");
		Double tb=(Double)b.get("t");
		if(ta==null||tb==null){
			if(ta==null) logIf(logMissingTimeErrors, "no t in: ta="+obToJson(a));
			if(tb==null) logIf(logMissingTimeErrors, "no t in: tb="+obToJson(b));
			throw new RuntimeException("Every node must have .t");
			/*This could be caused by t being 0 as in this code in Var*.js 2026-1-9: if(this.t){
				ret.t = this.t; //UTC time updated. not all code will use this. but each Var is a time-series of 2 numbers: position and velocity.
			}*/
		}
		boolean bTimeAllowed = isIncomingTimeAllowed(b,serverReceiveTime);
		if(!bTimeAllowed){
			logIf(logFutureRejects, "Rejecting future incoming node t="+tb+" serverReceiveTime="+serverReceiveTime+" node="+obToJson(b));
		}
		boolean bNewer=bTimeAllowed && tb>ta;
		NavigableMap newer=bNewer?b:a;

		TreeMap out=new TreeMap(JsonDS.mapKeyComparator);
		for(Object k:newer.keySet()){
			if(k.equals("t")||k.equals("tNet")||k.equals("pu")) continue;
			out.put(k,newer.get(k));			//local scalars once
		}
		out.put("t",bNewer?tb:ta);				//write .t once
		if(bNewer){
			if(tb>0) out.put("tNet",TimeIdNext());
		}else{
			double tNet=num(a,"tNet");
			if(tNet!=0) out.put("tNet",tNet);
		}

		NavigableMap pa=(NavigableMap)a.get("pu");
		NavigableMap pb=(NavigableMap)b.get("pu");
		if(pa!=null||pb!=null){
			TreeSet keys=new TreeSet(JsonDS.mapKeyComparator);
			if(pa!=null) keys.addAll(pa.keySet());
			if(pb!=null) keys.addAll(pb.keySet());

			TreeMap pu=new TreeMap(JsonDS.mapKeyComparator);
			for(Object k:keys){
				NavigableMap ca=pa==null?null:(NavigableMap)pa.get(k);
				NavigableMap cb=pb==null?null:(NavigableMap)pb.get(k);
				NavigableMap c = ca==null ? stampAcceptedIncoming(cb,serverReceiveTime) : (cb==null ? ca : mergeMaps(ca,cb,serverReceiveTime));
				if(c!=null) pu.put(k,c);
			}
			if(!pu.isEmpty()) out.put("pu",Collections.unmodifiableNavigableMap(pu));
		}
		return Collections.unmodifiableNavigableMap(out);
	}


	//If true, calls stringInStringOut in 1 shared thread so "static volatile NavigableMap V"
	//only touches 1 CPU core's cache so is faster, in theory, than every thread touching it.
	//Also we dont need to use synchronized or volatile on that if its single threaded.
	static boolean stringInStringOut_happensInOtherThread = true;

	//static final ExecutorService singleComputeThread = Executors.newSingleThreadExecutor(); //normal priority thread?
	static final ExecutorService singleComputeThread = Executors.newSingleThreadExecutor(r->{ //high priority thread
		Thread t = new Thread(r,"QuadCraftCompute");
		t.setPriority(Thread.MAX_PRIORITY-1);
		return t;
	});

	static String maybeAsync_stringInStringOut(String i){
		if(!stringInStringOut_happensInOtherThread){
			return stringInStringOut(i);
		}
		return CompletableFuture.supplyAsync(
			()->stringInStringOut(i),
			singleComputeThread
		).join();
	}


%><%
	String body = request.getReader().lines().reduce("", (a,b)->(a+b));
	if(body == null || body.trim().equals("")){
		body = "{}";
	}
	logIf(logUrl, "url="+request.getRequestURL()+" method="+request.getMethod());
	String i = body; //in
	String o = maybeAsync_stringInStringOut(i); //out
	response.setContentType("application/json");
	out.print(o);
%>
